name: Run Discord Bot

on:
  push:
    branches:
      - main  # Or any branch you want to trigger on push
  pull_request:
    branches:
      - main  # Optional: This will trigger for pull requests targeting `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up environment variables
      - name: Set up environment variables
        run: echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> $GITHUB_ENV

      # Step 5: Run the bot
      - name: Run Discord bot
        run: python main.py
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}  # Ensure bot token is in GitHub Secrets
